### ISSUE TITLE
Always having a trouble while downloading the second page

### ISSUE THREAD

**Issue by v0per** [Ghostish/instagram_batch_downloader#1]
Love this little thing!

But when I downloaded pics on IG with your downloader, it always popped out MAKE SURE YOU GIVE THE CORRECT USERNAME and can't continue to work since page 1 succeeded.

I'm using Windows 10 and operating this in Command with Python 3.7, as the pic below:

[https://imgur.com/a/dmBQQEa](url)

Thanks for your great work and hopefully hear from you!

**Comment by Ghostish** [comment]
Already fixed this, please try the new commit and let me know if you have any other problem 😃
