### ISSUE TITLE
Requirements setup error

### ISSUE THREAD

**Issue by ygornac** [Ghostish/instagram_batch_downloader#3]
Microsoft Windows [versão 10.0.18362.329]
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32

C:\>pip install requirements
Collecting requirements
ERROR: Could not find a version that satisfies the requirement requirements (from versions: none)
ERROR: No matching distribution found for requirements

C:\Users\ygorn\Downloads\instagram_batch_downloader-master>pip install requests
Successfully installed certifi-2019.6.16 chardet-3.0.4 idna-2.8 requests-2.22.0 urllib3-1.25.3

C:\>python go_spider.py -u NASA -m 5 -t video
getting info of NASA
'rhx_gis'
KeyError: Make sure you give the correct username
Downloaded 0 items
ig_spider.meta was saved

Contents: {"end_cursor": null, "username": "NASA", "last_page": 0, "download_type": "VIDEO", "max_page": 5}

**Comment by Ghostish** [comment]
I updated the code and now it won't be a problem.

**Comment by ygornac** [comment]
Confirmed, working perfectly.

Thank you.
